---
project_name: packer-provisioner-mondoo
builds:
  - main: main.go
    binary: packer-provisioner-mondoo
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - id: releases
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
checksum:
  name_template: "checksums.txt"