apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mondoo.fullname" . }}
  labels:
    {{- include "mondoo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mondoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mondoo.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mondoo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['mondoo','cr', '--config', '/etc/opt/mondoo/mondoo.yml', '-b', 'http://0.0.0.0:80', '--insecure']
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /Health/Check
              port: http
          readinessProbe:
            httpGet:
              path: /Health/Check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mondoo-agent-config
              mountPath: /etc/opt/mondoo
              readOnly: true
      volumes:
        - name: mondoo-agent-config
          secret:
            secretName: mondoo-agent-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
