---
project_name: terraform-provisioner-mondoo
builds:
  - main: main.go
    binary: terraform-provisioner-mondoo
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
archives:
  - id: releases
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*
checksum:
  name_template: "terraform-provisioner-mondoo-checksums.txt"