---
builds:
  - main: main.go
    binary: terraform-provisioner-mondoo
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64